# Generated by Django 4.2.7 on 2023-11-18 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_tag_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'categorymodel',
                'verbose_name_plural': 'categorymodels',
                'db_table': 'tagstable',
                'ordering': ['category_tag_name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=50, unique=True)),
                ('template_description', models.TextField()),
                ('urls_images', models.TextField()),
                ('template_category', models.ManyToManyField(related_name='templates', to='rating_templates.categorymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'templateModel',
                'verbose_name_plural': 'templatesModel',
                'db_table': 'templatestable',
                'ordering': ['template_name'],
            },
        ),
        migrations.CreateModel(
            name='TierListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.TextField(blank=True, null=True)),
                ('a', models.TextField(blank=True, null=True)),
                ('b', models.TextField(blank=True, null=True)),
                ('c', models.TextField(blank=True, null=True)),
                ('d', models.TextField(blank=True, null=True)),
                ('e', models.TextField(blank=True, null=True)),
                ('fk_template_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating_templates.templatemodel', to_field='template_name')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'TierlistModel',
                'verbose_name_plural': 'TierlistModels',
                'db_table': 'tierlisttable',
                'ordering': ['s', 'a', 'b', 'c', 'd', 'e'],
            },
        ),
    ]
