# Generated by Django 4.2.7 on 2023-11-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tierlistmodel',
            name='tierlist_name',
            field=models.CharField(default='NoName', max_length=50, unique=True),
        ),
    ]
