# Generated by Django 4.2.7 on 2023-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_templates', '0002_tierlistmodel_tierlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierlistmodel',
            name='tierlist_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
