# Generated by Django 4.2.7 on 2023-11-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating_templates', '0003_alter_tierlistmodel_tierlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierlistmodel',
            name='fk_template_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rating_templates.templatemodel', to_field='template_name'),
        ),
    ]
